### ISSUE TITLE
XML Schema validation on subdocument

### ISSUE THREAD

**Issue by hhv** [Armatiek/xslweb#13]
It would be great if Schema validation can be done only certain child elements. In our use case we generate 4 documents that will be written to disk. Before we write them to disk they need to be validated but they are hidden in the XML stream, several levels deep. So, an XPath to the right 'document' would be OK, but probably a namespaced element to match would be better. If the matched element and its children are considered to be a document and then validated that would make life easier.

**Comment by maartenkroon** [comment]
Hi Huib,

I am not sure if I understand your question completely. Is it a solution to create a separate validation pipeline that uses a XML schema with "multiple roots" that you can call from a main pipeline as "[nested pipeline](https://armatiek.github.io/xslweb/XSLWeb%20Developer%20Manual.html#nested-pipelines)"? Then could pass pass the (serialized) child element you want to validate as a request parameter.

Regards, Maarten

**Comment by hhv** [comment]
Hi Maarten,

that sounds like a solution, but I am not quite sure what you mean by "XML Schema with 'multiple roots'". 

Regards,
Huib.

**Comment by maartenkroon** [comment]
I mean an XML schema that contains multiple global element declarations and therefore can be used to validate parts/fragments of an XML document.

**Comment by hhv** [comment]
OK, thanks Maarten, that sounds like just what I need, I'll give it a try.

**Comment by hhv** [comment]
OK, that works, thanks Maarten. I have this now:


    <xsl:variable name="osp" as="element(output:serialization-parameters)">
      <output:serialization-parameters xmlns:output="http://www.w3.org/2010/xslt-xquery-serialization">
        <output:method value="xml"/>
        <output:encoding value="UTF-8"/>
        <output:version value="1.0"/>
        <output:indent value="no"/>
        <output:omit-xml-declaration value="yes"/>
      </output:serialization-parameters>
    </xsl:variable>
    
    <xsl:copy-of select="document(concat('xslweb://', $config:webapp-path, '/validation/xml-waardelijst.xml?xml=', encode-for-uri(ser:serialize(tooiwl:waardelijst, $osp))))" />


In the validation pipeline I have this:


    <pipeline:transformer name="validate1" xsl-path="deserialize-xml-parameter.xslt"/>
    
    <pipeline:schema-validator
      name="schema-validator"
      xsl-param-namespace="http://www.armatiek.com/xslweb/validation"
      xsl-param-name="schema-validation-report">
      <pipeline:schema-paths>
        <pipeline:schema-path>tooi-waardelijst.xsd</pipeline:schema-path>
      </pipeline:schema-paths>
    </pipeline:schema-validator>
    
    <pipeline:transformer name="schema-validation-result"
      xsl-path="show_schema_validation_result.xslt" log="false"/>

This generates \<error> elements when appropriate and nothing otherwise and it works. Thanks Maarten. It's not very efficient with the serialization and deserialization but for our use-case that does not matter.

**Comment by maartenkroon** [comment]
Hi Huib,

Passing nodes in the form of serialized strings as parameters to an nested/internal request is not very efficient indeed. With commit 5931abd2f9306306c20218b21b01b3dcb1759a15 all attributes that you store in the "parent" request using req:set-attribute($name, $value) will be available in the nested/internal request using req:get-attribute($name). That means you now can pass *any* sequence (including nodes) to the nested/internal request without the need for serialization. 

Regards,
Maarten

**Comment by hhv** [comment]
Thanks Maarten, that's excellent. I'll try it soon.
