### ISSUE TITLE
Attribute expire-time of the resource-serializer does not seem to have an effect

### ISSUE THREAD

**Issue by frankweenink** [Armatiek/xslweb#14]
Using expire-time on resource-serializer does not seem to have an effect on the cache expiration. It always returns 30 days (in seconds) in the HTTP response:

Cache-Control: public,max-age=2592000,must-revalidate

**Comment by maartenkroon** [comment]
Hi Frank,

I think it does work (just tested it), but this functionality was only added in commit 62088624bb1f0f411faa1d6a911176fdbdb792be, so after XSLWeb release 4.0.1 of XSLWeb. This feature is mentioned in the documentation of 4.01, which is wrong :-(

Which version of XSLWeb do you use?

In older versions you should be able to set the expire headers in the normal way using the resp:headers/resp:header tags.

Regards,
Maarten

**Comment by frankweenink** [comment]
Hi Maarten,

I'm using 4.0.1 so that explains it.

Thanks for looking into this.
