### ISSUE TITLE
Pipeline with xquery filter says "Could not determine destination"

### ISSUE THREAD

**Issue by pmasereeuw** [Armatiek/xslweb#17]
Hi Maarten,

I am creating an application that uses an xquery step in a pipeline. Unfortunately, I cannot get it to run. I created a small example webapp (attached) that reproduces the problem. The first step (XSLT) generates some xml, the second step filters it. I tested both steps. If I comment the xquery-step out, xslweb produces the right XML, but if I leave the xquery step in, I get an error:

`nl.armatiek.xslweb.error.XSLWebException: Could not determine destination
	at nl.armatiek.xslweb.web.servlet.XSLWebServlet.getDestination(XSLWebServlet.java:266)
	at nl.armatiek.xslweb.web.servlet.XSLWebServlet.executeRequest(XSLWebServlet.java:387)
	at nl.armatiek.xslweb.web.servlet.XSLWebServlet.service(XSLWebServlet.java:144)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
`

I can easily somehow work around it (e.g., by doing the filtering in XSLT), but I thought you might want to know. Logfiles also attached.
I am using the xslweb-ready-to-run-v4.0.1-linux-x64 version.

Best wishes for 2022 BTW

[xquerytest.zip](https://github.com/Armatiek/xslweb/files/7795535/xquerytest.zip)
[logs.zip](https://github.com/Armatiek/xslweb/files/7795537/logs.zip)
.

**Comment by pmasereeuw** [comment]
After writing the above, I thought the answer might be to replace `<pipeline:query  xquery-path=...>` with `<pipeline:transformer xquery-path=...>` but that does not help. I get the error `Transformer step must have an attribute "xsl-path"`. That means that the xslweb documentation for paragraph 2.1.2 (query step) needs correction.

**Comment by maartenkroon** [comment]
Hi Pieter,

Thanks for reporting this bug. I apparently only tested the query pipeline step in pipelines where it is the only step, not with a preceding transformation step... 

This issue is fixed in commit 1c796b7.

Maarten

**Comment by maartenkroon** [comment]
I also corrected the bug in the documentation (pipeline:transformer -> pipeline:query), see https://armatiek.github.io/xslweb/XSLWeb%20Developer%20Manual.html#query-step

**Comment by pmasereeuw** [comment]
@maartenkroon Supersnel! De fix werkt, en dat op oudejaarsdag! Mijn grote dank!
