### ISSUE TITLE
"The schema is invalid" in case of a Saxon-EE compiled XSLWeb

### ISSUE THREAD

**Issue by pmasereeuw** [Armatiek/xslweb#18]
Because I want to recompile a Saxon-JS stylesheet automatically, I compiled XSLWeb with -PSaxon-EE.
From that moment, xslweb refuses to start (inside Tomcat). In the log you see the message:
```
ERROR [main] - Could not open XSLWeb Context
org.xml.sax.SAXParseException: The schema is invalid
```
With some tracing, I found out that the report is about the first schema it tries to process in initXMLSchemas() in Context.java. It is the schema webapp.xsd. However, when I validate the schema in Oxygen, or when I validate a webapp.xml file with it, everything works fine.

I made the reference to the license file (licenseFileLocation in <saxon-config:configuration edition="EE" .. >) absolute, but that does not help.

My work-around is of course to compile the Saxon-JS stylesheet by hand and make the sef.json file a static resource, because with  Saxon-HE there are no problems.

**Comment by maartenkroon** [comment]
Hi Pieter,

The full error of Saxon's XML schema validation of webapp.xsd is:

```
Error on line 517 of ehcache-core.xsd:
   The type Q{http://www.ehcache.org/v3}persistable-memory-type-with-prop-subst has complex
  content so it cannot be derived by extension from the complex type
  Q{http://www.ehcache.org/v3}memory-type-with-prop-subst which has simple content
Schema processing failed: The schema is invalid
```

I am not sure if this error is justified or not; Xerces and Saxon 9 do not seem to report this error. I however decided to change all occurences of the JAXP call SchemaFactory.newInstance() to call the new method XMLUtils.getNonSaxonJAXPSchemaFactory(). This ensures that XSLWeb internal (ie non-Saxon) XML schema validation always uses the JDK's SchemaFactory.

See commit 3c51d54.

**Comment by pmasereeuw** [comment]
Hi Maarten,

That works, thank you. I think this issue is solved.

However, I get a lot of weird compilation errors when XSLWeb compiles the stylesheet, but I will have to investigate that myself.

Thanks for the quick fix!

**Comment by pmasereeuw** [comment]
.. forget the remark above about compilation errors, I quickly solved my own silly error  ;-) ..
