### ISSUE TITLE
enhancement: upgrade Saxon version 9.8 to 9.9

### ISSUE THREAD

**Issue by eluija** [Armatiek/xslweb#3]

**Comment by maartenkroon** [comment]
@eluija : In commit b1e01dd the Saxon dependency is upgraded from 9.8.0-8 to 9.9.1-7.

**Comment by eluija** [comment]
Thanks. 
Any plans to upgrade to release 10 of saxon ?

**Comment by maartenkroon** [comment]
Yes! When Saxon 9.9 is not recommended anymore as the "most stable version" (see http://saxon.sourceforge.net/), I will start upgrading.

**Comment by maartenkroon** [comment]
@eluija : XSLWeb version 4.0.0-RC1 uses Saxon version 10.2 (see https://github.com/Armatiek/xslweb/releases/tag/v4.0.0-RC1)

**Comment by eluija** [comment]
Thanks. Work fine.
