### ISSUE TITLE
macOS ready-to-run 4.0.1 contains a war with version "4.0.0".

### ISSUE THREAD

**Issue by hhv** [Armatiek/xslweb#9]
Hi,

I just downloaded the 4.0.1 ready-to-run version for macOS and unpacking that I noticed there's a war file in bin/jetty/jetty-base/webapps that's called "xslweb-4.0.0.war". I assume that is actually the 4.0.0 version of XSLWeb but I haven't checked it.

Huib.

**Comment by hhv** [comment]
Less relevant: in run-service.sh "4.0.0" is also mentioned: " STOP.KEY=xslweb_4_0_0"

**Comment by maartenkroon** [comment]
Hi Huib,

This is an "imperfection" in the build proces of the "ready-to-run" builds. The jar and stopkeys are indeed called 4.0.0 but the actual contents is 4.0.1. You can check this via the (still undocumented?) parameter "config:version" that is passed to every xslt transformation. I will try to fix this buid-process bug in a next release.
Maarten
